name: Build and Deploy

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@main

         - name: Install Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 12

         - name: Install dependencies
           run: npm install

         - name: Build React app
           run: npm run build

         - name: Archive artifacts
           uses: actions/upload-artifact@v2
           with:
              name: build-artifact
              path: build

   deploy:
      runs-on: ubuntu-latest

      needs: build

      steps:
         - name: Download artifacts
           uses: actions/download-artifact@v2
           with:
              name: build-artifact

         - name: Deploy to S3
           uses: jakejarvis/s3-sync-action@main
           with:
              args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
           env:
              AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
